### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by daehyeok** [mozilla/hglib-rust#2]
Hi, 
sorry for leave the question on the issue page.
But I'm trying to use this lib, so I want to check is it reliable or not.
And are you planning on publish it to crates.io?

**Comment by calixteman** [comment]
We don't use the lib for the moment but it isn't dead.
So feel free to make PRs to fix bugs or to add some missing commands or missing tests.
I'll publish it in the week.

**Comment by daehyeok** [comment]
Thank @calixteman  
I wrote test cases based on original python test code(python-hglib). and i found problems on below test modules. 

### Missing test cases compared to python-hglib. Updated(2020.3.19)
- Not implemented feature
  - [ ]  context
in python-hglib, context is wrapper of log function, but provide extra feature(e.g. _manifest)
  - [x] encoding
  - [x] grep
  - [x] Summary


- BUG(test fail)
  - [x] import
  API can't handling string patch

- Missing
  - [ ] test-hglib.py
    open/close test

**Comment by calixteman** [comment]
I remember now: I didn't publish because need to have some test for each command.
Anyway I added a test for manifest (and fix the empty line).

**Comment by calixteman** [comment]
I'm fixing update command, I should have finished tomorrow.

**Comment by daehyeok** [comment]
I'm fixing outgoing/incoming.

**Comment by daehyeok** [comment]
I'm fixing grep command. Python test cases look ridiculous and not correct. but anyway i think i can fix.

**Comment by calixteman** [comment]
I fixed import and I'm taking summary

**Comment by calixteman** [comment]
Taking context and we should be almost good and ready for a release.

**Comment by calixteman** [comment]
I'll fix the missing context later.
Anyway a great thank you for your help.
And the it's available on crates.io: https://crates.io/crates/hglib-rs
